#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

# LBM parameters
nx, ny = 250, 250  # Grid size
lattice_length = 1
tau = 1.00  # Relaxation time
omega = 1.0 / tau  # Relaxation parameter
iterations = 1000  # Number of iterations

# D2Q9 Lattice velocities and weights
velocities = np.array([[0, 0], [1, 0], [0, 1], [-1, 0],
                      [0, -1], [1, 1], [-1, 1], [-1, -1], [1, -1]])
weights = np.array([4 / 9] + [1 / 9] * 4 + [1 / 36] * 4)

inverse_velocity_index = [0, 3, 4, 1, 2, 7, 8, 5, 6]

# Initialize macroscopic variables
rho = np.ones((nx, ny))  # Density
u = np.zeros((nx, ny))  # Velocity in x direction
v = np.zeros((nx, ny))  # Velocity in y direction

# add a point perturbation to the pressure field
rho[125, 125] = 0.001

# Initialize distribution function (feq)
f = np.ones((nx, ny, 9)) * (rho[..., None] * weights)

# calculate equilibrium distribution function from u,v,rho
def equilibrium_distribution(rho, u, v):
    usqr = u**2 + v**2
    feq = np.zeros((nx, ny, 9))

    # Calculate eu for each velocity direction
    for i in range(9):
        eu = velocities[i, 0] * u + velocities[i, 1] * \
            v  # Dot product for each direction
        feq[:, :, i] = rho * weights[i] * \
            (1 + 3 * eu + 9 / 2 * eu**2 - 3 / 2 * usqr)

    return feq

# Streaming step
def streaming(f):
    for i, vel in enumerate(velocities):
        f[:, :, i] = np.roll(f[:, :, i], shift=vel, axis=(0, 1))
    return f


# Main LBM loop
for it in range(iterations):
    feq = equilibrium_distribution(rho, u, v)
    f = omega * feq + (1 - omega) * f  # Collision step
    f = streaming(f)  # Streaming step

    # Compute macroscopic variables
    rho = np.sum(f, axis=2)
    u = np.sum(f * velocities[:, 0], axis=2) / rho
    v = np.sum(f * velocities[:, 1], axis=2) / rho

    # Plot the velocity magnitude every 500 iterations
    if it % 10 == 0:
        plt.clf()  # Clear the current figure to avoid overlapping
        plt.imshow(np.sqrt(u**2 + v**2).T, cmap='gnuplot')
        plt.colorbar()
        plt.title(f'Iteration {it}')
        plt.pause(0.005)

plt.show()
